import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import StoryblokProvider from "@/app/storyblok.provider";
import {apiPlugin, storyblokInit} from "@storyblok/react/rsc";

storyblokInit({
  accessToken: "cxpZQOw5vS1RMweA36KeUgtt",
  use: [apiPlugin],
});

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <StoryblokProvider>
      <body className={inter.className}>{children}</body>
    </StoryblokProvider>
    </html>
  );
}
