import type { Metadata } from 'next';
import { Sora } from 'next/font/google';
import './globals.css';
import StoryblokProvider from '@/app/storyblok.provider';
import { apiPlugin, storyblokInit } from '@storyblok/react/rsc';
import { Header } from '@/app/header';

storyblokInit({
  accessToken: 'cxpZQOw5vS1RMweA36KeUgtt',
  use: [apiPlugin],
});

const inter = Sora({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <StoryblokProvider>
        <body className={inter.className}>
          <main className='mx-auto max-w-screen-xl px-6 md:px-8'>
            <Header />
            {children}
          </main>
        </body>
      </StoryblokProvider>
    </html>
  );
}
